NAME: miniapps-ticket20-api

RUN_UNIT_TEST: false
IGNORE_UNIT_TEST_ERROR: true
TEST_IMAGE_NAME: miniapps-ticket20-api
TEST_IMAGE_TAG: testimage-latest

# SONAR SCAN
RUN_SONAR: false
IGNORE_SONAR_QUALITY: true
SONAR_PROJECT_KEY: miniapps-ticket20-api
SONAR_HOST_URL: https://sonar.sv-dga.com
SONAR_SCAN_SOURCE_CODE_TARGET: .

# Build spec
IMAGE_NAME: miniapps-ticket20-api

# AWS
AWS_REGION: ap-southeast-7
AWS_ROLE_TO_ASSUME: arn:aws:iam::877502627026:role/github

# Ingress
DOMAIN: superapps-th.cloud
SUB_DOMAIN: miniapps-dev
PATH_PATTERN: /cp/transit/ticket20/api
PATH_HEALTH_CHECK: /cp/transit/ticket20/api/healthcheck

dev:
  AWS_REGION: ap-southeast-7
  AWS_ROLE_TO_ASSUME: arn:aws:iam::340752823852:role/github
  CLUSTER_NAME: miniapps-dev
  SERVICE_NAME: miniapps-ticket20-api-dev
  TASK_DEFINITION_NAME: miniapps-ticket20-api-dev
  CONTAINER_NAME: miniapps-ticket20-api-dev

  DOMAIN: opendata-dga.cloud
  SUB_DOMAIN: miniapps2-dev

uat:
  AWS_REGION: ap-southeast-7
  AWS_ROLE_TO_ASSUME: arn:aws:iam::340752823852:role/github
  CLUSTER_NAME: miniapps-uat
  SERVICE_NAME: miniapps-ticket20-api-uat
  TASK_DEFINITION_NAME: miniapps-ticket20-api-uat
  CONTAINER_NAME: miniapps-ticket20-api-uat

  DOMAIN: opendata-dga.cloud
  SUB_DOMAIN: miniapps2-uat

prod:
  AWS_REGION: ap-southeast-7
  AWS_ROLE_TO_ASSUME: arn:aws:iam::877502627026:role/github
  CLUSTER_NAME: miniapps-cluster-prod
  SERVICE_NAME: miniapps-ticket20-api-prod
  TASK_DEFINITION_NAME: miniapps-ticket20-api-prod
  CONTAINER_NAME: miniapps-ticket20-api-prod

  DOMAIN: superapps-th.cloud
  SUB_DOMAIN: miniapps
