FROM node:22-alpine3.21 AS base

USER root
RUN apk add tzdata && \
    ln -s /usr/share/zoneinfo/Asia/Bangkok /etc/localtime


FROM base

USER node
WORKDIR /build

COPY source/nest-cli.json .

COPY source/package.json .
COPY source/package-lock.json .

COPY source/tsconfig.json .
COPY source/tsconfig.build.json .

COPY source/src ./src

RUN npm ci