FROM node:22-alpine3.21

RUN apk add tzdata && \
    ln -s /usr/share/zoneinfo/Asia/Bangkok /etc/localtime

WORKDIR /usr/src/app

COPY source/nest-cli.json .
COPY source/jest.config.js .

COPY source/package.json .
COPY source/package-lock.json .

COPY source/tsconfig.json .
COPY source/tsconfig.build.json .
COPY source/tslint.json .

COPY source/src ./src

RUN npm ci

CMD ["npm", "run", "test:cov"]
