export enum ProviderName {
    ENVIRONMENT_CONFIG = 'ENVIRONMENT_CONFIG',
    HTTP_CLIENT = 'HTTP_CLIENT',
    EGOV_ADAPTER = 'EGOV_ADAPTER',

    AUTHENTICATION_SERVICE = 'AUTHENTICATION_SERVICE',
    ACCESS_TOKEN_SIGNER = 'ACCESS_TOKEN_SIGNER',
    REFRESH_TOKEN_SIGNER = 'REFRESH_TOKEN_SIGNER',
    TOKENIZATION_SERVICE = 'TOKENIZATION_SERVICE',

    ERROR_FACTORY_SERVICE = 'ERROR_FACTORY_SERVICE',
    LOGGER_SERVICE = 'LOGGER_SERVICE',
    REQUEST_CONTEXT_SERVICE = 'REQUEST_CONTEXT_SERVICE',
    ACCESS_LOGGER_SERVICE = 'ACCESS_LOGGER_SERVICE',

    USE_CASE_AUTHENTICATION = 'USE_CASE_AUTHENTICATION',
    USE_CASE_CREATE_JWT = 'USE_CASE_CREATE_JWT',

    MONGO_DATASOURCE = 'MONGO_DATASOURCE',
    CARD_REPOSITORY = 'CARD_REPOSITORY',
    CARD_ENTITY_MAPPER = 'CARD_ENTITY_MAPPER',

}
